### ISSUE TITLE
Ontwerp Analyse

### ISSUE THREAD

**Issue by Jason2426** [Jesse-Kramer/connect-your-tribe-profile-card#2]
Wat is mooi en wat werkt goed? 
SOB standingon business
Leuk en simpel ontwerp, ook leuke bewegende animatie en goede text vormgeving gebruikt.

Wat kan beter en wat werk niet goed? 
 
Het kaartje is niet volledig responsive en past niet op volledig op mijn laptop hier kan aan gewerkt worden en is simpel op te lossen als je mobile first bent gestart. De animatie voor de hele kaart vind ik wel nice maar voor andere is het misschien een beetje onnodig en haalt het de focus weg van de tekst.

Verder prima visitekaartje, probeer bij dit soort projecten iets geks te maken want dit is niet een opdracht voor de opdrachtgever dus je kan maken wat je wilt.

**Comment by Jesse-Kramer** [comment]
Dankjewel, ik zal kijken naar de responsiveheid en ook naar de animatie (misschien wat minder maken).
